language: node_js
node_js:
- 4.2.1
- 6.9.2
before_install:
- git config --global user.name "Travis CI Test"
- git config --global user.email "test@test.com"
- export docuBranch='master'
- export NODE_ENV=prod
- export RESULT_LOC='https://'$DEPLOY_TOKEN'@github.com/yaas/chewie-sample-result.git'
- if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
install:
- npm run prepare
script:
- npm run init
- npm run prepare-deploy
- npm run preparePushResult
- npm run pushResult
- npm run test:ui
env:
  global:
  - secure: uJSm5TsS3D7StnJfFIsCqUJXRNrLg5ZxCux9GtHej9xIzG4pCNQA93jX7q0y+2/XwEL2KgTbJdrxw9OrWq1gjqXfYVDvEbam4/TBxX1XL239ZHQlwNzVYALSo/1JUAbydEfQ4ziNNVxvrSSKoK1jRnKAu9bUVdzlEpHZ8RBK8+uFYbRPHPdSJhK5GDk28oQXb+ItvTqM7ikwuGQW169Q8oJbBezpMDq2befihp/VqgGMdEjrg+nahdhxQSDQ9JUNBaEyDrZzS2HQ1vv2r4XheZoKjpfmKKa230aXW1NUMLGij2gSxypljyWWyFKptEoxoAJ8OioMU94by6vnKnWYOfBy500yy7jl7U1/4l544MFWAXNhWJ0A1GLLL5n1XMjN6SITHj/tlQZv+oeL/Xnzvjnd3u+q1pAQWWQDOaLqTX/qfyiqJaZxMzgrT+PAhWOvpVlv2WuzCnld8Rn8EDAVRcKe//QELJ+Xmf1PeJB1MzGWqp69EjaFgMc0EJkd6XtA82JHgAOIGQSYi4ObyHlMz8PPH8QyWrAkNgLqP98VG2JqVc785ERsnoi8SHpypAeTCtX9ToEDrKz6b2K+HgryGxaCNApM1BkGr8EwKO0qmYCklq8AbU2pK9SaYAZ7/s1pnZWwmV83oaborvu7DGMCrYMLFyuJbNlRVgOQr5+zwtA=
  - secure: h8ZiTEO8/4WFYyKz9S0H2Q5/KpGEqOz7ZndGznzbaYxSADWQ7Dycb4JD22PvSKRVK7E1mwBgUv758kkIw5HHRhxDMFTTFLrkh8mdbL4ZhqNJodMx33Xz4NRoKDEiSABOqfltk7w4JTO8ZFWRHlAPNSgd+97dq9x3iWhgmfkHRQwusVnPL8lBXxy/ELKI2ENEi4sIm/8t6EmfX+kVPO1hMPHs5ojo2BRZga7QScxVExPSAomw8pUdhnNaUXDquunL47b/r4O4thO1ljozIm4To6h6cGAQKDZehIIkewCwtAPQMr15RBu2lkte2uqrnOju+4c2R8bGxgL/YqpsVgj3bnJ+zRdvSgNLg7i1O/8nfX/ntZ7rWv0aX/m6guHR5NjMIhCXQ7niFwhb8qp/8kxBJ9I56OYtxGkhnMlOHuABrowKXmZOpKrRdXu2KRrz7stBApdPp9ZhtczqIn/VPkUcWbARPF350E+n0Kxtm6W+jB+MLkg774Ct3CAg/GDaBuWtE51i0bDGwdavTu11GVaab4jWoIckP16pINQycxgHZ5uZFMbDpbnf0PkKB4hXkteiTikVKj+WJIvDwtDsIAdMwGV9+T97Xff66DexNd1PGPV6TSlSSlIW6DfKrGO0/2SnUhA7YEa35D/4vttwD8o6HnO2ZYclBx0fiXQvMJMgT8o=
branches:
  only:
  - master
