sudo: required
language: node_js
node_js:
- 4.2.1
- 6.9.1
before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi #make sure that npm version is at least 3.x
install:
- git config --global user.name "Travis CI Test"
- git config --global user.email "test@test.com"
- export RESULT_LOC='https://'$DEPLOY_TOKEN'@github.com/yaas/chewie-sample-result.git'
- npm run prepare
script:
- npm run init
- npm run compile
- export docuBranch=gh-pages
- npm run preparePushResult
- npm run pushResult
env:
  global:
  - secure: Ncm/EB5JMqpSAEDITE3jBMWOGg1l51P2ooX6xwTh6yMe/FuloN3mIuzBKVVWUOoOt5oBr6ejyA8eKbzIOrMTzkNd1Eb5tGU+3Y4lEXrFevZwnDctX1EedqxbTKpbOPk0l7h2Wx1s/EElyJtMRu2tPKg3V0HwSfoh9EOQI7kqojdynFFUByfj2AL5L6QqrB7AJde9aokS1iO/ZAhX3VDfdTPKCxcKrwm8Zkemfa64/gYiYvrtgdoD8bTI2lxZxAB1+ssG9WJUfywGVICVA79YjbCJdusK/vrnsqENlHXf9TkHFcqFNrv1JIKi1IFbOAgwDT+P02qp9ykSxfifKoSKJ/75Tr1mas3M3MU008dfZ5CuVIGsSxn2s48kroRqDUqhYUqM9ioNt5nRL/qz881zwDzmXwVL32lUnYOMyieYhtJEb0I7/JRXaRplGbZO7ctqTcF/NFyFM13pGsnbkOU7W9eVdnnQWaO+9BkZ64hmzCTENQwQAiecyXcG+UdGxXHj3caW4DBTr9GlMIwfL49FK8kcN+26a0kJH0XT7ka940R+CjcUef0fkE1/cthPO338uWb7tVr2oUzoHu+/pvrgGNEriUzJG7TsUWMN7CYCZB/1P2O/+q3WjePDlOskUPQC+qQ0ScE9Xp23JtXuQeR5hVNLsBOt6uK3jS7p6IXj25w=
