sudo: required
language: node_js
node_js:
- 4.2.1
- 6.9.1
before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
install:
- git config --global user.name "Travis CI Test"
- git config --global user.email "test@test.com"
- export RESULT_LOC='https://'$DEPLOY_TOKEN'@github.com/yaas/chewie-sample-result.git'
- npm run prepare
script:
- npm run init
- npm run compile
- export docuBranch=gh-pages
- npm run preparePushResult
- npm run pushResult
env:
  global:
  - secure: fYio+Ep0HLQLWBCkfroC67dyO5JzJdxmwxM2MFlZGbh/vUWoWZNPxsuFiqcHCmBZUGwP/S+1mXM/onjUmdDbLHWUeyStmUOHEksoRvlpyOTbvC4YfFEowww1zKZk99a0zyS2Ma0zAEbqOuTPS+0EHjqtyJ5mNRxrXEOb1NXz9sbRgyYWNHmKH+htIEzz11NAWCmX/RE6kBMy7C4HQzvauNpt4r0jI6CatyUOLA5d4kkuTUFWSpmmyQx+RDpC89oQ5EB30eVpP0lq0L/u24ZPa+K+DZwvsxl6EY4oXqXjtw0VSyGISgGCgCvErg+/yqlN1pr4QMN4tns2H92FG3KYDZ2052vPiLa9z/fAZ+p+O640nrzyqjmpaPl7SVpc/oJZsTTzr6WiyB4SAJUL2QcOJf4mS4Ol2GCBv1pr/wiEM7IV8XgAi/oc7LYCWNjgJNKiZwsocCG4MA5cYdnExxckOKi3aDBvfBgtRzAnOPqkq1g/9w5gEs9Y8xQ944EpN3MFnUxDuSPQA702eFqfb4/9WReG5NLJuqSwZ7u80Swksvao4Qfv9SQeFYXk5xUairY3jf9C5XuZSAMqax+3vASdO/ZMKvaFf7vT7W6tVkngIzGNwX7kgzbd8zLFR37UNomzBpZF5945WroW/nx8fzoOhtsL3StRyqKbX3e3aza1+ZE=
